Repository ponylang/net_ssl, pull requests merged in 2022-02, with the labels that each got.

#65 Add nodoc annotation to test code
  net_ssl/_test.pony
Labels: discuss during sync

#66 Support for using ponyup on Windows
  .release-notes/66.md
  make.ps1
Labels: changelog - added, discuss during sync

#69 Update to work with object capabilities changes in Pony 0.49.0
  .release-notes/obj-cap.md
  examples/simple-example/simple-example.pony
  net_ssl/_test.pony
Labels: changelog - fixed, discuss during sync

#70 Update to address PonyTest package being renamed
  .github/workflows/pr.yml
  .release-notes/ponytest.md
  net_ssl/_test.pony
Labels: changelog - fixed, discuss during sync

#71 Remove hardcoding of Visual Studio version
  .release-notes/vs.md
  README.md
  make.ps1
  net_ssl/ssl_context.pony
Labels: changelog - fixed, discuss during sync

#72 Run PRs against release builds again
  .github/workflows/pr.yml
Labels: discuss during sync
